const List<Map<String, String>> watches = [
  {
    'image': 'assets/images/watch1.png',
    'title': 'Leipzig Black',
    'brand': 'Nomos Glashütte',
    'details': 'Gold IP Stainless Steel',
    'price': '\$334.99',
  },
  {
    'image': 'assets/images/watch2.webp',
    'title': 'Macedon A11B',
    'brand': 'Aevig',
    'details': 'Stainless Steel Case',
    'price': '\$1,010.00',
  },
  {
    'image': 'assets/images/watch3.png',
    'title': 'Meccanico Silver',
    'brand': 'Meccaniche Veloci',
    'details': 'Leather Strap',
    'price': '\$146.00',
  },
  {
    'image': 'assets/images/watch4.webp',
    'title': 'Classic Automatic',
    'brand': 'Tissot',
    'details': 'Sapphire Crystal',
    'price': '\$498.00',
  },
  {
    'image': 'assets/images/watch5.webp',
    'title': 'Chopard Luxury',
    'brand': 'Chopard',
    'details': 'Diamond Bezel',
    'price': '\$799.00',
  },
  {
    'image': 'assets/images/watch6.webp',
    'title': 'Fossil Gen 6',
    'brand': 'Fossil',
    'details': 'Smartwatch Features',
    'price': '\$249.00',
  },
  {
    'image': 'assets/images/watch7.png',
    'title': 'Omega Seamaster',
    'brand': 'Omega',
    'details': 'Water Resistant',
    'price': '\$3,299.00',
  },
  {
    'image': 'assets/images/watch8.png',
    'title': 'Tag Heuer Carrera',
    'brand': 'Tag Heuer',
    'details': 'Chronograph Function',
    'price': '\$5,499.00',
  },
  {
    'image': 'assets/images/watch9.webp',
    'title': 'Rolex Submariner',
    'brand': 'Rolex',
    'details': 'Ceramic Bezel',
    'price': '\$10,500.00',
  },
  {
    'image': 'assets/images/watch10.png',
    'title': 'Breitling Navitimer',
    'brand': 'Breitling',
    'details': 'Slide Rule Bezel',
    'price': '\$8,250.00',
  },
  {
    'image': 'assets/images/watch11.png',
    'title': 'Patek Philippe Nautilus',
    'brand': 'Patek Philippe',
    'details': 'Stainless Steel Bracelet',
    'price': '\$35,000.00',
  },
  {
    'image': 'assets/images/watch2.webp',
    'title': 'Audemars Piguet Royal Oak',
    'brand': 'Audemars Piguet',
    'details': 'Octagonal Bezel',
    'price': '\$28,000.00',
  },
  {
    'image': 'assets/images/watch3.png',
    'title': 'Hublot Big Bang',
    'brand': 'Hublot',
    'details': 'Carbon Fiber Case',
    'price': '\$15,000.00',
  },
  {
    'image': 'assets/images/watch4.webp',
    'title': 'IWC Portugieser',
    'brand': 'IWC',
    'details': 'Automatic Movement',
    'price': '\$12,000.00',
  },
  {
    'image': 'assets/images/watch5.png',
    'title': 'Panerai Luminor',
    'brand': 'Panerai',
    'details': 'Cushion-Shaped Case',
    'price': '\$9,500.00',
  },
  {
    'image': 'assets/images/watch6.webp',
    'title': 'Jaeger-LeCoultre Reverso',
    'brand': 'Jaeger-LeCoultre',
    'details': 'Reversible Case',
    'price': '\$7,800.00',
  },
  {
    'image': 'assets/images/watch7.png',
    'title': 'Cartier Tank',
    'brand': 'Cartier',
    'details': 'Rectangular Case',
    'price': '\$6,500.00',
  },
  {
    'image': 'assets/images/watch9.webp',
    'title': 'Longines Master Collection',
    'brand': 'Longines',
    'details': 'Moon Phase Display',
    'price': '\$2,800.00',
  },
  {
    'image': 'assets/images/watch8.png',
    'title': 'Seiko Presage',
    'brand': 'Seiko',
    'details': 'Enamel Dial',
    'price': '\$1,200.00',
  },
  {
    'image': 'assets/images/watch2.webp',
    'title': 'Citizen Eco-Drive',
    'brand': 'Citizen',
    'details': 'Solar-Powered',
    'price': '\$450.00',
  },
];